/**
 * Hand-written subset of the database schema, enough to type the tables the
 * app touches today. Replace with `npx supabase gen types typescript` output
 * once the project is linked; the shape is identical.
 */

export type ItemKind = "task" | "followup" | "note" | "goal";
export type LinkKind = "related" | "step" | "blocks";
export type LinkStatus = "confirmed" | "suggested" | "dismissed";
export type ItemStatus = "open" | "waiting" | "done" | "archived";
export type ItemPriority = "low" | "normal" | "high";
export type InboxStatus =
  | "pending"
  | "processing"
  | "processed"
  | "needs_review"
  /** Deleted from the inbox: kept, out of every list, restorable by Undo. */
  | "discarded"
  | "failed";
export type CaptureSource = "web" | "api" | "voice" | "share";
export type Recurrence =
  | "daily"
  | "weekdays"
  | "weekly"
  | "biweekly"
  | "monthly"
  | "quarterly"
  | "yearly";
export type PersonRole = "waiting_on" | "mentioned" | "owner";

export type InboxItemRow = {
  id: string;
  user_id: string;
  raw_text: string;
  source: CaptureSource;
  status: InboxStatus;
  ai_result: unknown | null;
  ai_confidence: number | null;
  ai_model: string | null;
  ai_error: string | null;
  item_id: string | null;
  attachment_path: string | null;
  created_at: string;
  processed_at: string | null;
};

export type ItemRow = {
  id: string;
  user_id: string;
  kind: ItemKind;
  title: string;
  body: string | null;
  source_text: string | null;
  status: ItemStatus;
  priority: ItemPriority | null;
  due_at: string | null;
  workspace_id: string | null;
  project_id: string | null;
  organization_id: string | null;
  category: string | null;
  tags: string[];
  inbox_item_id: string | null;
  completed_at: string | null;
  recurrence: Recurrence | null;
  /** The completed occurrence this one was spawned from. */
  recurred_from: string | null;
  reminded_at: string | null;
  attachment_path: string | null;
  /** Generated by Postgres; never written. */
  content_hash: string;
  created_at: string;
  updated_at: string;
};

export type WorkspaceRow = {
  id: string;
  user_id: string;
  name: string;
  slug: string;
  color: string | null;
  sort_order: number;
  created_at: string;
};

export type ProjectRow = {
  id: string;
  user_id: string;
  workspace_id: string | null;
  name: string;
  description: string | null;
  status: "active" | "archived";
  created_at: string;
  updated_at: string;
};

export type PersonRow = {
  id: string;
  user_id: string;
  name: string;
  aliases: string[];
  organization_id: string | null;
  notes: string | null;
  created_at: string;
};

export type PushSubscriptionRow = {
  id: string;
  user_id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  user_agent: string | null;
  created_at: string;
  last_success_at: string | null;
};

export type NotificationLogRow = {
  id: string;
  user_id: string;
  kind: string;
  local_date: string;
  sent_at: string;
};

export type ItemEmbeddingRow = {
  item_id: string;
  user_id: string;
  content_hash: string;
  /** pgvector text form: "[0.1,0.2,...]". */
  embedding: string;
  updated_at: string;
};

/**
 * A connection between two items.
 * - related: no direction; stored once, read both ways.
 * - step:    `from` is a step toward the goal `to`; `position` orders the steps.
 * - blocks:  `from` has to be done before `to` can start.
 */
export type ItemLinkRow = {
  user_id: string;
  from_item_id: string;
  to_item_id: string;
  kind: LinkKind;
  status: LinkStatus;
  position: number | null;
  created_at: string;
};

/** Where a node sits on the map. `node_id` is "item:<uuid>", "project:<uuid>", or "person:<uuid>". */
export type MapPositionRow = {
  user_id: string;
  node_id: string;
  x: number;
  y: number;
  /** True once dragged by hand; the layout never moves a pinned node. */
  pinned: boolean;
  updated_at: string;
};

/** The last good copy of an outside system's description of itself. `source` is "ceco". */
export type ExternalScopeRow = {
  user_id: string;
  source: string;
  payload: unknown;
  fetched_at: string;
};

/** A CECO page an item is about. `path` is CECO's own, e.g. "/trucking/jobboard". */
export type ItemCecoPageRow = {
  user_id: string;
  item_id: string;
  path: string;
  created_at: string;
};

export type ItemPersonRow = {
  user_id: string;
  item_id: string;
  person_id: string;
  role: PersonRole;
};

type Table<Row, Insert> = {
  Row: Row;
  Insert: Insert;
  Update: Partial<Insert>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      inbox_items: Table<
        InboxItemRow,
        Partial<Omit<InboxItemRow, "raw_text">> & { raw_text: string }
      >;
      items: Table<
        ItemRow,
        Partial<Omit<ItemRow, "kind" | "title" | "content_hash">> & {
          kind: ItemKind;
          title: string;
        }
      >;
      workspaces: Table<
        WorkspaceRow,
        Partial<Omit<WorkspaceRow, "name" | "slug">> & { name: string; slug: string }
      >;
      projects: Table<
        ProjectRow,
        Partial<Omit<ProjectRow, "name">> & { name: string }
      >;
      people: Table<
        PersonRow,
        Partial<Omit<PersonRow, "name">> & { name: string }
      >;
      item_people: Table<
        ItemPersonRow,
        Partial<Omit<ItemPersonRow, "item_id" | "person_id">> & {
          item_id: string;
          person_id: string;
        }
      >;
      item_links: Table<
        ItemLinkRow,
        Partial<Omit<ItemLinkRow, "from_item_id" | "to_item_id">> & {
          from_item_id: string;
          to_item_id: string;
        }
      >;
      external_scopes: Table<
        ExternalScopeRow,
        Partial<Omit<ExternalScopeRow, "source" | "payload">> & { source: string; payload: unknown }
      >;
      item_ceco_pages: Table<
        ItemCecoPageRow,
        Partial<Omit<ItemCecoPageRow, "item_id" | "path">> & { item_id: string; path: string }
      >;
      map_positions: Table<
        MapPositionRow,
        Partial<Omit<MapPositionRow, "node_id" | "x" | "y">> & {
          node_id: string;
          x: number;
          y: number;
        }
      >;
      push_subscriptions: Table<
        PushSubscriptionRow,
        Partial<Omit<PushSubscriptionRow, "endpoint" | "p256dh" | "auth">> & {
          endpoint: string;
          p256dh: string;
          auth: string;
        }
      >;
      notification_log: Table<
        NotificationLogRow,
        Partial<Omit<NotificationLogRow, "kind" | "local_date">> & {
          kind: string;
          local_date: string;
        }
      >;
      item_embeddings: Table<
        ItemEmbeddingRow,
        Partial<Omit<ItemEmbeddingRow, "item_id" | "content_hash" | "embedding">> & {
          item_id: string;
          content_hash: string;
          embedding: string;
        }
      >;
    };
    Views: Record<string, never>;
    Functions: {
      items_to_embed: {
        Args: { max_count?: number };
        Returns: {
          id: string;
          user_id: string;
          title: string;
          body: string | null;
          source_text: string | null;
          content_hash: string;
        }[];
      };
      related_items: {
        Args: { source_id: string; match_count?: number; min_similarity?: number };
        Returns: { item_id: string; similarity: number }[];
      };
      match_items: {
        Args: { query_embedding: string; match_count?: number; min_similarity?: number };
        Returns: { item_id: string; similarity: number }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
